-- À exécuter dans Supabase > SQL Editor
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text not null,
  category text not null check (category in ('Sneakers','Vêtements','Accessoires')),
  size text not null,
  condition text not null,
  price numeric(10,2) not null check (price > 0),
  color text default '',
  description text default '',
  details jsonb not null default '[]'::jsonb,
  vinted_url text not null,
  image_urls jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.products enable row level security;
create policy "Catalogue public en lecture" on public.products for select using (active = true);
insert into storage.buckets (id, name, public) values ('product-images','product-images',true) on conflict (id) do update set public=true;
