"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Edit3, ImagePlus, LogOut, DownloadCloud, PackagePlus, Save, Sparkles, Trash2, X } from "lucide-react";
import type { Product } from "../products";

const empty = {name:"",brand:"",category:"Sneakers",size:"",condition:"Neuf",price:"",color:"",description:"",details:"",vintedUrl:""};
export default function AdminPage(){
 const [token,setToken]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [products,setProducts]=useState<Product[]>([]); const [form,setForm]=useState(empty); const [editing,setEditing]=useState<Product|null>(null); const [files,setFiles]=useState<FileList|null>(null); const [open,setOpen]=useState(false); const [loading,setLoading]=useState(false); const [analyzing,setAnalyzing]=useState(false); const [importing,setImporting]=useState(false); const [message,setMessage]=useState("");
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL; const anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
 useEffect(()=>{const saved=sessionStorage.getItem("storeimr_admin_token");if(saved){setToken(saved);loadProducts(saved)}},[]);
 async function loadProducts(auth=token){const r=await fetch("/api/products");const d=await r.json();setProducts(d.products||[])}
 async function login(e:FormEvent){e.preventDefault();setLoading(true);setMessage("");try{const r=await fetch(`${url}/auth/v1/token?grant_type=password`,{method:"POST",headers:{"content-type":"application/json",apikey:anon||""},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error("Email ou mot de passe incorrect");sessionStorage.setItem("storeimr_admin_token",d.access_token);setToken(d.access_token);await loadProducts(d.access_token)}catch(e){setMessage(e instanceof Error?e.message:"Connexion impossible")}finally{setLoading(false)}}
 function startNew(){setEditing(null);setForm(empty);setFiles(null);setOpen(true)}
 function startEdit(p:Product){setEditing(p);setForm({name:p.name,brand:p.brand,category:p.category,size:p.size,condition:p.condition,price:String(p.price),color:p.color,description:p.description,details:p.details.join("\n"),vintedUrl:p.vintedUrl});setFiles(null);setOpen(true)}
 async function analyzePhoto(){const first=files?.[0];if(!first){setMessage("Sélectionne d’abord une photo");return}setAnalyzing(true);setMessage("");try{const fd=new FormData();fd.append("image",first);const r=await fetch("/api/ai-product",{method:"POST",headers:{authorization:`Bearer ${token}`},body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||"Analyse impossible");const s=d.suggestion;setForm(current=>({...current,name:s.name||current.name,brand:s.brand||current.brand,category:s.category||current.category,color:s.color||current.color,condition:s.condition||current.condition,description:s.description||current.description,details:Array.isArray(s.details)?s.details.join("\n"):current.details}));setMessage("Les champs ont été proposés par l’IA. Vérifie-les avant d’enregistrer.")}catch(e){setMessage(e instanceof Error?e.message:"Analyse impossible")}finally{setAnalyzing(false)}}
 async function save(e:FormEvent){e.preventDefault();setLoading(true);setMessage("");const fd=new FormData();Object.entries(form).forEach(([k,v])=>fd.append(k,v));if(editing)fd.append("existingImages",JSON.stringify(editing.imageUrls||[]));Array.from(files||[]).forEach(f=>fd.append("images",f));const endpoint=editing?`/api/products/${editing.id}`:"/api/products";const r=await fetch(endpoint,{method:editing?"PUT":"POST",headers:{authorization:`Bearer ${token}`},body:fd});const d=await r.json();setLoading(false);if(!r.ok){setMessage(d.error||"Enregistrement impossible");return}setOpen(false);setMessage(editing?"Article modifié":"Article ajouté");await loadProducts()}
 async function importVinted(){setImporting(true);setMessage("");try{const r=await fetch("/api/vinted/import",{method:"POST",headers:{authorization:`Bearer ${token}`}});const d=await r.json();if(r.status===401){sessionStorage.removeItem("storeimr_admin_token");setToken("");throw new Error(d.error||"Ta session a expiré. Reconnecte-toi.")}if(!r.ok)throw new Error(d.error||"Import impossible");setMessage(d.imported?`${d.imported} article${d.imported>1?"s":""} importé${d.imported>1?"s":""} depuis Vinted.`:"Ton dressing est déjà à jour.");await loadProducts()}catch(e){setMessage(e instanceof Error?e.message:"Import Vinted impossible")}finally{setImporting(false)}}
 async function remove(p:Product){if(!confirm(`Supprimer ${p.name} ?`))return;const r=await fetch(`/api/products/${p.id}`,{method:"DELETE",headers:{authorization:`Bearer ${token}`}});if(r.ok){setMessage("Article supprimé");await loadProducts()}}
 function logout(){sessionStorage.removeItem("storeimr_admin_token");setToken("")}
 if(!url||!anon)return <main className="admin-login"><div><img src="/storeimr-logo.svg" alt="StoreIMR"/><h1>Configuration requise</h1><p>Ajoute les variables Supabase dans Vercel pour activer l’administration.</p></div></main>;
 if(!token)return <main className="admin-login"><form onSubmit={login}><img src="/storeimr-logo.svg" alt="StoreIMR"/><span>ESPACE PROPRIÉTAIRE</span><h1>Connexion admin</h1><p>Cette page est réservée à la gestion de StoreIMR.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Mot de passe<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{message&&<div className="admin-message error">{message}</div>}<button disabled={loading}>{loading?"Connexion…":"Se connecter"}</button><Link href="/"><ArrowLeft/> Retour à la boutique</Link></form></main>;
 return <main className="admin-dashboard"><header><Link href="/" className="logo-link"><img src="/storeimr-logo.svg" alt="StoreIMR"/></Link><div><Link href="/">Voir la boutique</Link><button onClick={logout}><LogOut/> Déconnexion</button></div></header><section className="admin-title"><div><span>TABLEAU DE BORD</span><h1>Mes articles</h1><p>{products.length} article{products.length>1?"s":""} dans le catalogue</p></div><div className="admin-title-actions"><button className="vinted-import" onClick={importVinted} disabled={importing}><DownloadCloud/> {importing?"Synchronisation…":"Importer mon Vinted"}</button><button onClick={startNew}><PackagePlus/> Ajouter un article</button></div></section><section className="admin-overview"><article><span>ARTICLES EN LIGNE</span><b>{products.length}</b><small>Catalogue actif</small></article><article><span>VALEUR DU STOCK</span><b>{products.reduce((sum,p)=>sum+p.price,0).toFixed(0)} €</b><small>Prix de vente total</small></article><article><span>PHOTOS PUBLIÉES</span><b>{products.reduce((sum,p)=>sum+(p.imageUrls?.length||0),0)}</b><small>Visuels produits</small></article></section>{message&&<div className="admin-message">{message}</div>}<div className="admin-list-heading"><div><span>INVENTAIRE</span><h2>Catalogue produits</h2></div><button onClick={startNew}><PackagePlus/> Nouveau</button></div><section className="admin-products">{products.length===0?<div className="admin-empty"><PackagePlus/><h2>Aucun article</h2><p>Ajoute ton premier produit avec ses photos et son lien Vinted.</p><button onClick={startNew}>Ajouter un article</button></div>:products.map(p=><article key={p.id}><div className="admin-product-photo" style={{backgroundImage:`url(${p.imageUrls?.[0]||"/storeimr-hero.png"})`}}></div><div><span>{p.brand} · {p.category}</span><h2>{p.name}</h2><p>Taille {p.size} · {p.condition}</p></div><b>{p.price} €</b><div className="admin-row-actions"><button onClick={()=>startEdit(p)}><Edit3/> Modifier</button><button className="danger" onClick={()=>remove(p)}><Trash2/></button></div></article>)}</section>
 {open&&<div className="admin-modal"><div className="admin-dialog"><button className="close" onClick={()=>setOpen(false)}><X/></button><span>{editing?"MODIFIER L’ARTICLE":"NOUVEL ARTICLE"}</span><h2>{editing?editing.name:"Ajouter au catalogue"}</h2><form onSubmit={save}><div className="admin-form-grid"><label>Nom du produit<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Marque<input value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})} required/></label><label>Catégorie<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Sneakers</option><option>Vêtements</option><option>Accessoires</option></select></label><label>Taille<input value={form.size} onChange={e=>setForm({...form,size:e.target.value})} required/></label><label>État<input value={form.condition} onChange={e=>setForm({...form,condition:e.target.value})} required/></label><label>Prix (€)<input type="number" min="1" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} required/></label><label>Couleur<input value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></label><label className="wide">Lien de l’annonce Vinted<input type="url" placeholder="https://www.vinted.fr/items/..." value={form.vintedUrl} onChange={e=>setForm({...form,vintedUrl:e.target.value})} required/></label><label className="wide">Description<textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="wide">Détails — un par ligne<textarea rows={4} value={form.details} onChange={e=>setForm({...form,details:e.target.value})}/></label><label className="wide image-upload"><ImagePlus/><b>Photos du produit</b><span>Tu peux sélectionner plusieurs photos</span><input type="file" accept="image/*" multiple onChange={e=>setFiles(e.target.files)}/><button type="button" className="ai-fill" onClick={analyzePhoto} disabled={analyzing||!files?.length}><Sparkles/> {analyzing?"Analyse en cours…":"Remplir les champs avec l’IA"}</button></label></div>{message&&<div className="admin-message error">{message}</div>}<button className="save" disabled={loading}><Save/> {loading?"Enregistrement…":"Enregistrer l’article"}</button></form></div></div>}
 </main>
}
