"use client";
import { useMemo, useState } from "react";
import { ArrowRight, Camera, Check, Heart, Menu, Search, ShieldCheck, ShoppingBag, SlidersHorizontal, Sparkles, Truck, X } from "lucide-react";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { products, type Product } from "./products";

const categories = ["Tout", "Sneakers", "Vêtements", "Accessoires"] as const;
export default function Storefront() {
 const [category,setCategory]=useState<(typeof categories)[number]>("Tout"); const [query,setQuery]=useState(""); const [cart,setCart]=useState<Product[]>([]); const [favorites,setFavorites]=useState<number[]>([]); const [sent,setSent]=useState(false);
 const visible=useMemo(()=>products.filter(p=>(category==="Tout"||p.category===category)&&`${p.name} ${p.brand} ${p.size}`.toLowerCase().includes(query.toLowerCase())),[category,query]); const total=cart.reduce((s,p)=>s+p.price,0);
 async function sendRequest(){await fetch("/api/inquiries",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({items:cart.map(p=>p.id),total})});setSent(true)}
 return <main>
  <div className="announcement">Livraison rapide en France & Luxembourg <span>•</span> Prix avantageux pour les abonnés Vinted</div>
  <header className="site-header"><a className="brand" href="#top"><span>STORE</span><b>IMR</b></a><nav className="desktop-nav"><a href="#nouveautes">Nouveautés</a><a href="#catalogue">Catalogue</a><a href="#engagements">Nos engagements</a></nav><div className="header-actions"><button aria-label="Rechercher" onClick={()=>document.getElementById("search")?.focus()}><Search/></button><a href="https://www.vinted.fr" target="_blank">Vinted <ArrowRight/></a>
   <Sheet><SheetTrigger className="cart-button"><ShoppingBag/><span>{cart.length}</span></SheetTrigger><SheetContent className="cart-sheet"><SheetHeader><SheetTitle>Votre sélection</SheetTitle><SheetDescription>Réservez vos pièces avant qu’elles ne partent.</SheetDescription></SheetHeader>{sent?<div className="success"><Check/><h3>Demande envoyée</h3><p>Je vous recontacte rapidement pour finaliser.</p></div>:<><div className="cart-list">{cart.length===0?<p className="empty">Votre panier est vide.</p>:cart.map((p,i)=><div className="cart-line" key={`${p.id}-${i}`}><div><b>{p.name}</b><span>Taille {p.size}</span></div><strong>{p.price} €</strong><button onClick={()=>setCart(cart.filter((_,x)=>x!==i))}><X/></button></div>)}</div>{cart.length>0&&<div className="cart-footer"><div><span>Total</span><strong>{total} €</strong></div><button onClick={sendRequest}>Demander la réservation <ArrowRight/></button><small>Paiement et livraison confirmés directement avec StoreIMR.</small></div>}</>}</SheetContent></Sheet><button className="mobile-menu"><Menu/></button></div></header>
  <section className="hero" id="top"><div className="hero-copy"><span className="eyebrow"><Sparkles/> Sélection à prix juste</span><h1>Du style.<br/><em>Sans compromis.</em></h1><p>Sneakers et vêtements soigneusement sélectionnés, vérifiés et prêts à vivre une nouvelle histoire.</p><div className="hero-cta"><a href="#catalogue">Voir la sélection <ArrowRight/></a><a className="ghost" href="https://www.vinted.fr" target="_blank">Suivre sur Vinted</a></div><div className="hero-stats"><div><b>100%</b><span>articles vérifiés</span></div><div><b>24–48h</b><span>envoi rapide</span></div><div><b>4,9/5</b><span>satisfaction</span></div></div></div><div className="hero-image"><div className="drop-card"><span>DROP 09</span><b>Nouvelles pièces</b><small>Disponibles maintenant</small></div></div></section>
  <section className="catalog" id="catalogue"><div className="section-head" id="nouveautes"><div><span className="kicker">LA SÉLECTION DU MOMENT</span><h2>Pièces fraîchement ajoutées</h2></div><p>Chaque article est disponible en un seul exemplaire.</p></div><div className="catalog-tools"><div className="categories">{categories.map(c=><button className={category===c?"active":""} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><label className="search"><Search/><input id="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Marque, taille…"/><SlidersHorizontal/></label></div><div className="product-grid">{visible.map(p=><article className="product-card" key={p.id}><div className="product-image" style={{backgroundPosition:p.position}}><span>{p.condition}</span><button className={favorites.includes(p.id)?"liked":""} onClick={()=>setFavorites(favorites.includes(p.id)?favorites.filter(id=>id!==p.id):[...favorites,p.id])}><Heart/></button></div><div className="product-info"><div><span>{p.brand}</span><h3>{p.name}</h3><p>Taille {p.size} · {p.color}</p></div><strong>{p.price} €</strong></div><button className="add" onClick={()=>setCart([...cart,p])}>Ajouter à la sélection <ShoppingBag/></button></article>)}</div>{visible.length===0&&<div className="no-results">Aucune pièce ne correspond à votre recherche.</div>}</section>
  <section className="promise" id="engagements"><div className="promise-title"><span>POURQUOI STOREIMR</span><h2>La seconde main,<br/>en toute confiance.</h2></div><div className="promise-grid"><div><ShieldCheck/><b>Pièces vérifiées</b><p>État, taille et détails contrôlés avant chaque mise en ligne.</p></div><div><Truck/><b>Expédition soignée</b><p>Emballage propre et envoi rapide avec suivi.</p></div><div><Heart/><b>Service humain</b><p>Une question ? Je vous réponds directement et rapidement.</p></div></div></section>
  <footer><a className="brand light" href="#top"><span>STORE</span><b>IMR</b></a><p>Une sélection pensée à Metz, disponible partout en France et au Luxembourg.</p><div><a href="https://www.vinted.fr" target="_blank">Vinted</a><a href="#"><Camera/> Instagram</a><a href="mailto:contact@storeimr.fr">Contact</a></div><small>© 2026 StoreIMR. Tous droits réservés.</small></footer>
 </main>
}
